add_newline = true

format = """ $directory$git_branch$git_status $character"""

[character]
success_symbol = "[\\$](white)"
error_symbol = "[\\$](bold bright-red)"
vimcmd_symbol = "[\\$](white)"
vimcmd_replace_symbol = "[\\$](white)"
vimcmd_visual_symbol = "[\\$](white)"

[directory]
style = "bold purple"
truncate_to_repo = true
truncation_length = 3
format = '[$path]($style)($read_only_style)'

[git_branch]
symbol= " [[\\[](bold blue)󰊢 ](bold blue)"
style = "bright-blue"
format = '[$symbol$branch(:$remote_branch) ]($style)'

[git_status]
ahead = "⇡${count}"
behind = "⇣${count}"
conflicted = '$count'
deleted = " "
diverged = '↑$ahead_count↓$behind_count'
modified = "󱇬 "
renamed = " "
staged = "󰝒 "
stashed = "󰬲 "
untracked = " "
format = "[$all_status$ahead_behind](yellow)[\\]](bold blue)"
