# append newlines to command outputs
add_newline = true

# custom format
format = """
$sudo\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$git_metrics\
$docker_context\
$line_break\
$jobs\
$character"""

# prompt chars
[character]
success_symbol = "[ %](bold white)"
error_symbol = "[ %](bold bright-red)"
vimcmd_symbol = "[ %](bold white)"
vimcmd_replace_symbol = "[ %](bold orange)"
vimcmd_visual_symbol = "[ %](bold magenta)"

[directory]
style = "#87FF5F bold"
truncate_to_repo = true
truncation_length = 6
format = ' [$path]($style)($read_only_style)'

[git_branch]
symbol = "[「󰊢 ](bold blue)"
style = "bright-blue"
format = '[$symbol$branch(:$remote_branch) ]($style)'

[git_commit]
only_detached = true
tag_symbol = "/"
tag_disabled = false
format = "[「󰊢 $hash$tag ](bold bright-blue)"

[git_status]
ahead = "⇡${count}"
behind = "⇣${count}"
conflicted = '$count'
deleted = " "
diverged = '↑$ahead_count↓$behind_count'
modified = "󱇬 "
renamed = " "
staged = "󰝒 "
stashed = "󰬲 "
untracked = " "
format = "[$all_status$ahead_behind](yellow)"

[git_metrics]
disabled = false
format = '[」](bold blue)'

[docker_context]
symbol = '󰡨'
format = '[ $symbol $version ](bright-black)'

[jobs]
symbol = " +"
number_threshold = 4
